//! Option A consumption: generate a per-model `list.html` override that the
//! framework serves via `RUSTIO_TEMPLATE_DIR` (the same seam navigation uses).
//!
//! Doctrine note (see DESIGN_REASONING R-001 / R-002): rustio-admin forbids a
//! schema-driven *runtime* — presentation is reshaped at build time, never by a
//! framework hook. So we emit a template, not data, exactly like `_sidebar.html`.
//!
//! The framework's `list.html` chrome (search, filters, sort, bulk, pagination,
//! empty state) is reproduced **verbatim** from the template we target — those
//! sections depend only on framework context (`filters`, `sort_fields`, `rows`,
//! …), never on the column set. Only the two `{% for f in fields %}` column
//! loops (header + body cell) are replaced with view-spec-driven columns. This
//! keeps every non-column feature byte-identical to the framework and isolates
//! drift to a single, testable seam.
//!
//! Targets rustio-admin's `assets/templates/admin/list.html` contract. The
//! version it mirrors is recorded in `LIST_TEMPLATE_BASED_ON`; bump it when the
//! framework's list chrome changes.

use crate::spec::{TableView, ViewCell};

/// The framework `list.html` version this override mirrors (for drift tracking).
pub const LIST_TEMPLATE_BASED_ON: &str = "rustio-admin list.html · console masthead + data board";

/// Build the per-model `list.html` override for one table view.
pub fn build_list_template(project: &str, view: &TableView) -> String {
    // Visible cells lead the list (primary first, then secondary in declared
    // order). Detail/hidden never appear in the list mode.
    let mut visible: Vec<&ViewCell> = view
        .cells
        .iter()
        .filter(|c| c.role == "primary" || c.role == "secondary")
        .collect();
    visible.sort_by_key(|c| if c.role == "primary" { 0 } else { 1 });

    let thead = visible
        .iter()
        .map(|c| {
            format!(
                "        <th class=\"rio-th--text\">{}</th>",
                esc(&label_of(c))
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let tbody = visible
        .iter()
        .enumerate()
        .map(|(i, c)| body_cell(c, i == 0))
        .collect::<Vec<_>>()
        .join("\n");

    let header = format!(
        "{{# ============================================================\n\
         \x20# GENERATED by rustio-design — DO NOT EDIT THIS FILE.\n\
         \x20#\n\
         \x20#   rustio-admin record list (view layer)\n\
         \x20#   project: {project} · table: {table}\n\
         \x20#   mirrors: {based}\n\
         \x20#\n\
         \x20# Source of truth: the [views.{table}] section of rustio.design.toml,\n\
         \x20# decided in design/DESIGN_ARCHITECTURE.md (see DESIGN_REASONING).\n\
         \x20# Edit the spec, then run `rustio-design build`. Hand edits here are\n\
         \x20# reverted on the next build and flagged by `rustio-design check`.\n\
         \x20# Only the column header + body cells are view-spec-driven; all other\n\
         \x20# chrome is reproduced verbatim from the framework template.\n\
         \x20# ============================================================ #}}\n",
        project = project,
        table = view.table,
        based = LIST_TEMPLATE_BASED_ON,
    );

    LIST_BASE
        .replace("__RIO_THEAD_COLS__", &thead)
        .replace("__RIO_TBODY_CELLS__", &tbody)
        .replace("__RIO_HEADER__", header.trim_end())
}

/// Humanise a lead field name for a column header (`booked_at` → `Booked at`).
fn label_of(cell: &ViewCell) -> String {
    let lead = &cell.members[0];
    let mut s = lead.replace('_', " ");
    if let Some(first) = s.get_mut(0..1) {
        first.make_ascii_uppercase();
    }
    s
}

/// Render one `<td>` for a cell, honouring compose style. The first (primary)
/// cell links to the edit page like the framework's leading column.
fn body_cell(cell: &ViewCell, primary: bool) -> String {
    let value = compose_value(cell);
    if primary {
        let lead = &cell.members[0];
        format!(
            "        <td class=\"rio-td--text\">\n\
             \x20         <a class=\"rio-cell-primary\" href=\"/admin/{{{{ admin_name }}}}/{{{{ row.id }}}}/edit\">{value}</a>\n\
             \x20       </td>",
            value = if cell.members.len() == 1 {
                format!("{{{{ row[\"{lead}\"]|default(value=row.id) }}}}")
            } else {
                value
            },
        )
    } else {
        format!("        <td class=\"rio-td--text\">{value}</td>")
    }
}

/// Render a cell's value(s) per compose style using framework-safe markup.
fn compose_value(cell: &ViewCell) -> String {
    let acc = |name: &str| format!("{{{{ row[\"{name}\"]|default(value='') }}}}");
    if cell.members.len() == 1 {
        return acc(&cell.members[0]);
    }
    let lead = acc(&cell.members[0]);
    let trail = &cell.members[1..];
    match cell.style.as_str() {
        "badge" => {
            let pills = trail
                .iter()
                .map(|m| format!("<span class=\"rio-pill\">{}</span>", acc(m)))
                .collect::<Vec<_>>()
                .join(" ");
            format!("<span class=\"rio-cell-compose\">{lead} {pills}</span>")
        }
        "inline" => {
            let rest = trail
                .iter()
                .map(|m| {
                    format!(
                        "<span style=\"color:var(--rio-text-mute)\">{}</span>",
                        acc(m)
                    )
                })
                .collect::<Vec<_>>()
                .join(" · ");
            format!("<span class=\"rio-cell-compose\">{lead} <span style=\"color:var(--rio-text-mute)\">·</span> {rest}</span>")
        }
        // stacked (default): lead on top, trailing muted beneath.
        _ => {
            let rest = trail
                .iter()
                .map(|m| {
                    format!(
                        "<span style=\"display:block;font-size:12px;color:var(--rio-text-mute)\">{}</span>",
                        acc(m)
                    )
                })
                .collect::<Vec<_>>()
                .join("");
            format!("<span class=\"rio-cell-compose\"><span style=\"display:block\">{lead}</span>{rest}</span>")
        }
    }
}

fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// The framework `list.html`, reproduced verbatim except for the generated
/// header (`__RIO_HEADER__`) and the two column seams (`__RIO_THEAD_COLS__`,
/// `__RIO_TBODY_CELLS__`). Keeping the chrome byte-identical means search,
/// filters, sort, bulk actions, and pagination behave exactly as upstream.
const LIST_BASE: &str = r####"__RIO_HEADER__
{% extends "admin/_base.html" %}

{% macro filter_icon(kind) -%}
{%- if kind == "date_range" -%}{{ icon("clock", class="rio-icon") }}
{%- elif kind == "fk_autocomplete" -%}{{ icon("database", class="rio-icon") }}
{%- elif kind == "multi_select" -%}{{ icon("menu", class="rio-icon") }}
{%- else -%}{{ icon("flag", class="rio-icon") }}
{%- endif -%}
{%- endmacro %}

{% macro filter_active(group) -%}
{%- if group.kind == "date_range" and group.has_active_range -%}1
{%- elif group.kind == "multi_select" and group.multi_selected -%}1
{%- elif group.kind == "fk_autocomplete" and group.fk_selected_id -%}1
{%- elif group.kind not in ["date_range", "multi_select", "fk_autocomplete"] and group.current -%}1
{%- endif -%}
{%- endmacro %}

{% macro filter_body(group, admin_name, search_query, active_sort_field, active_sort_dir, active_per_page_override, csrf_token) %}
{% if group.kind == "fk_autocomplete" %}
<form method="get" action="/admin/{{ admin_name }}" class="rio-fk-autocomplete" data-rio-fk-autocomplete data-rio-fk-lookup-url="{{ group.fk_lookup_url }}" data-rio-fk-field-name="{{ group.field }}">
  {% for pair in group.hidden_pairs %}<input type="hidden" name="{{ pair[0] }}" value="{{ pair[1] }}">{% endfor %}
  {% if search_query %}<input type="hidden" name="q" value="{{ search_query }}">{% endif %}
  {% if active_sort_field %}<input type="hidden" name="sort" value="{{ active_sort_field }}"><input type="hidden" name="dir" value="{{ active_sort_dir }}">{% endif %}
  {% if active_per_page_override %}<input type="hidden" name="per_page" value="{{ active_per_page_override }}">{% endif %}
  <input type="hidden" name="{{ group.field }}" value="{{ group.fk_selected_id }}" data-rio-fk-id>
  <div class="rio-fk-autocomplete-wrap">
    <input type="search" class="rio-input rio-fk-autocomplete-input" value="{{ group.fk_selected_label or group.fk_selected_id }}" placeholder="Search {{ group.fk_target_label }}…" autocomplete="off" data-rio-fk-search>
    <ul class="rio-fk-autocomplete-results" data-rio-fk-results hidden></ul>
  </div>
  <div class="rio-fk-autocomplete-actions">
    <button type="submit" class="rio-btn rio-btn--primary rio-btn--sm">Apply</button>
    {% if group.fk_selected_id %}<a href="{{ group.all_link }}" class="rio-btn rio-btn--secondary rio-btn--sm">Clear</a>{% endif %}
  </div>
</form>
{% elif group.kind == "multi_select" %}
<form method="get" action="/admin/{{ admin_name }}" class="rio-multi-select">
  {% for pair in group.hidden_pairs %}<input type="hidden" name="{{ pair[0] }}" value="{{ pair[1] }}">{% endfor %}
  {% if search_query %}<input type="hidden" name="q" value="{{ search_query }}">{% endif %}
  {% if active_sort_field %}<input type="hidden" name="sort" value="{{ active_sort_field }}"><input type="hidden" name="dir" value="{{ active_sort_dir }}">{% endif %}
  {% if active_per_page_override %}<input type="hidden" name="per_page" value="{{ active_per_page_override }}">{% endif %}
  <ul class="rio-multi-select-options">
    {% for opt in group.options %}
    <li><label class="rio-multi-select-option"><input type="checkbox" name="{{ group.field }}" value="{{ opt.value }}"{% if opt.selected %} checked{% endif %}><span>{{ opt.label }}</span></label></li>
    {% endfor %}
  </ul>
  <div class="rio-multi-select-actions">
    <button type="submit" class="rio-btn rio-btn--primary rio-btn--sm">Apply</button>
    {% if group.multi_selected %}<a href="{{ group.all_link }}" class="rio-btn rio-btn--secondary rio-btn--sm">Clear</a>{% endif %}
  </div>
</form>
{% elif group.kind == "date_range" %}
<form method="get" action="/admin/{{ admin_name }}" class="rio-date-range">
  {% for pair in group.hidden_pairs %}<input type="hidden" name="{{ pair[0] }}" value="{{ pair[1] }}">{% endfor %}
  {% if search_query %}<input type="hidden" name="q" value="{{ search_query }}">{% endif %}
  {% if active_sort_field %}<input type="hidden" name="sort" value="{{ active_sort_field }}"><input type="hidden" name="dir" value="{{ active_sort_dir }}">{% endif %}
  {% if active_per_page_override %}<input type="hidden" name="per_page" value="{{ active_per_page_override }}">{% endif %}
  <label class="rio-date-range-field"><span class="rio-date-range-label-text">From</span><input type="date" name="{{ group.date_from_name }}" value="{{ group.date_from_value }}" class="rio-input rio-date-range-input"></label>
  <label class="rio-date-range-field"><span class="rio-date-range-label-text">To</span><input type="date" name="{{ group.date_to_name }}" value="{{ group.date_to_value }}" class="rio-input rio-date-range-input"></label>
  <div class="rio-date-range-actions">
    <button type="submit" class="rio-btn rio-btn--primary rio-btn--sm">Apply</button>
    {% if group.has_active_range %}<a href="{{ group.all_link }}" class="rio-btn rio-btn--secondary rio-btn--sm">Clear</a>{% endif %}
  </div>
</form>
{% else %}
<div class="rio-chip-row">
  <a href="{{ group.all_link }}" class="rio-chip{% if not group.current %} is-active{% endif %}">All</a>
  {% for opt in group.options %}
  <a href="{{ opt.link }}" class="rio-chip{% if opt.selected %} is-active{% endif %}">{{ opt.label }}</a>
  {% endfor %}
</div>
{% endif %}
{% endmacro %}


{% block content %}
<nav class="rio-crumbs"><a href="/admin">Home</a><span class="rio-crumb-sep">·</span><span class="rio-crumb-current">{{ display_name }}</span></nav>

<div class="rio-masthead-top">
  <div>
    <h1>{{ display_name }}</h1>
    <p class="rio-masthead-desc">Every {{ singular_name|lower }} rustio generated for {{ app_name }} — searchable, sortable, production-ready.</p>
  </div>
  <div class="rio-masthead-cta">
    <a class="rio-btn rio-btn--secondary rio-btn--md" href="{{ csv_export_url }}" download>{{ icon("download") }} Export</a>
    {% if not read_only %}
    <a class="rio-btn rio-btn--primary rio-btn--md" href="/admin/{{ admin_name }}/new">{{ icon("plus") }} Add {{ singular_name }}</a>
    {% endif %}
  </div>
</div>

{# ---- Command bar ---- #}
<div class="rio-cmdbar">
  <form method="get" action="/admin/{{ admin_name }}" class="rio-search rio-search--lg rio-search--hero{% if search_query %} rio-search--filled{% endif %}" role="search">
    <span class="rio-search-icon">{{ icon("search") }}</span>
    <input class="rio-input" type="search" name="q" value="{{ search_query }}" placeholder="Search {{ display_name|lower }}…" aria-label="Search">
    {% for pair in active_filter_pairs %}<input type="hidden" name="{{ pair[0] }}" value="{{ pair[1] }}">{% endfor %}
    {% if active_sort_field %}<input type="hidden" name="sort" value="{{ active_sort_field }}"><input type="hidden" name="dir" value="{{ active_sort_dir }}">{% endif %}
    {% if active_per_page_override %}<input type="hidden" name="per_page" value="{{ active_per_page_override }}">{% endif %}
    <button type="submit" class="rio-search-go" tabindex="-1">Search</button>
  </form>

  {% if filters %}
    {% for group in filters %}{% if loop.index <= 2 %}
    <div class="rio-dropdown" data-rio-dropdown>
      <button type="button" class="rio-btn rio-btn--secondary rio-btn--lg rio-dropdown-toggle{% if filter_active(group) %} is-active{% endif %}" aria-haspopup="true" aria-expanded="false">{{ filter_icon(group.kind) }} {{ group.label }} {{ icon("chevron-down", class="rio-chev") }}</button>
      <div class="rio-dropdown-panel rio-menu" role="dialog" aria-label="{{ group.label }}"><div class="rio-dropdown-section">{{ filter_body(group, admin_name, search_query, active_sort_field, active_sort_dir, active_per_page_override, csrf_token) }}</div></div>
    </div>
    {% endif %}{% endfor %}
    {% if filters|length > 2 %}
    <div class="rio-dropdown" data-rio-dropdown>
      <button type="button" class="rio-btn rio-btn--secondary rio-btn--lg rio-dropdown-toggle" aria-haspopup="true" aria-expanded="false">{{ icon("filter") }} More filters{% if active_filter_count > 0 %} <span class="rio-dropdown-badge">{{ active_filter_count }}</span>{% endif %} {{ icon("chevron-down", class="rio-chev") }}</button>
      <div class="rio-dropdown-panel rio-menu" role="dialog" aria-label="More filters">
        {% for group in filters %}{% if loop.index > 2 %}<div class="rio-dropdown-section"><span class="rio-dropdown-label">{{ group.label }}</span>{{ filter_body(group, admin_name, search_query, active_sort_field, active_sort_dir, active_per_page_override, csrf_token) }}</div>{% endif %}{% endfor %}
        {% if active_filter_count > 0 %}<div class="rio-dropdown-footer"><a href="{{ clear_all_filters_link }}" class="rio-btn rio-btn--secondary rio-btn--sm">Clear all</a></div>{% endif %}
      </div>
    </div>
    {% endif %}
  {% endif %}

  {% if sort_fields %}
  <div class="rio-dropdown" data-rio-dropdown>
    <button type="button" class="rio-btn rio-btn--secondary rio-btn--lg rio-dropdown-toggle" aria-haspopup="true" aria-expanded="false">{{ icon("sliders") }} Sort: {{ current_sort_field_label }} {{ icon("chevron-down", class="rio-chev") }}</button>
    <div class="rio-dropdown-panel rio-menu" role="dialog" aria-label="Sort">
      <div class="rio-dropdown-section"><span class="rio-dropdown-label">Sort by</span>
        <div class="rio-dropdown-menu">
          <a href="{{ default_sort_link }}" class="rio-menu-item{% if not active_sort_field %} is-active{% endif %}">Default order</a>
          {% for sf in sort_fields %}<a href="{{ sf.asc_link }}" class="rio-menu-item{% if sf.is_active %} is-active{% endif %}">{{ sf.label }}</a>{% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% if active_sort_field %}<a class="rio-btn rio-btn--secondary rio-btn--lg" href="{{ sort_dir_toggle_link }}" title="Switch direction">{{ icon("arrow-up-down") }} {{ current_sort_dir_label }}</a>{% endif %}
  {% endif %}

  {% if per_page_options %}
  <div class="rio-dropdown" data-rio-dropdown>
    <button type="button" class="rio-btn rio-btn--secondary rio-btn--lg rio-dropdown-toggle" aria-haspopup="true" aria-expanded="false">{{ icon("table") }} {{ current_per_page_label }} / page {{ icon("chevron-down", class="rio-chev") }}</button>
    <div class="rio-dropdown-panel rio-menu" role="dialog" aria-label="Rows per page"><div class="rio-dropdown-section"><div class="rio-chip-row">{% for opt in per_page_options %}<a href="{{ opt.link }}" class="rio-chip{% if opt.is_active %} is-active{% endif %}">{{ opt.label }}</a>{% endfor %}</div></div></div>
  </div>
  {% endif %}

  {% if search_query or active_filter_count > 0 %}<a class="rio-btn rio-btn--subtle rio-btn--lg" href="{{ clear_all_filters_link }}">{{ icon("rotate-ccw") }} Reset</a>{% endif %}
</div>

{% if active_filter_pills %}
<div class="rio-active-filters" role="region" aria-label="Active filters">
  <span class="rio-active-filters-label">Active</span>
  {% for pill in active_filter_pills %}<span class="rio-active-pill"><span class="rio-active-pill-key">{{ pill.label }}:</span> {{ pill.value_label }} <a href="{{ pill.remove_link }}" class="rio-active-pill-x" aria-label="Remove {{ pill.label }} filter">×</a></span>{% endfor %}
  <a href="{{ clear_all_filters_link }}" class="rio-active-filters-clear">Clear all</a>
</div>
{% endif %}

{# ---- Board ---- #}
{% if not read_only %}
<form method="post" action="/admin/{{ admin_name }}/bulk_delete" class="rio-bulk-form" data-rio-bulk>
<input type="hidden" name="_csrf" value="{{ csrf_token }}">
<input type="hidden" name="_ids" value="" data-rio-bulk-ids>
<div class="rio-bulkbar" role="region" aria-live="polite" aria-label="Bulk actions">
  <span class="rio-bulkbar-count"><strong data-rio-bulk-count>0</strong> selected</span>
  <button type="button" class="rio-btn rio-btn--ghost rio-btn--sm" data-rio-bulk-clear>Clear</button>
  <span style="margin-inline-start:auto;display:flex;gap:8px">
    <button type="submit" class="rio-btn rio-btn--subtle rio-btn--sm" style="color:var(--rio-danger)">{{ icon("trash") }} Delete selected</button>
    {% for btn in bulk_action_buttons %}<button type="submit" formaction="{{ btn.form_action }}" class="rio-btn rio-btn--secondary rio-btn--sm{% if btn.destructive %} rio-btn--danger{% endif %}">{{ btn.label }}</button>{% endfor %}
  </span>
</div>
{% endif %}

<div class="rio-board">
  {% if rows %}
  <div style="overflow:auto">
  <table class="rio-dtable">
    <thead>
      <tr>
        {% if not read_only %}<th class="col-check"><input type="checkbox" class="rio-row-checkbox-all" data-rio-bulk-all aria-label="Select all"></th>{% endif %}
__RIO_THEAD_COLS__
        <th class="col-act">&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      {% for row in rows %}
      <tr>
        {% if not read_only %}<td class="col-check"><input type="checkbox" class="rio-row-checkbox" data-rio-bulk-row value="{{ row.id }}" aria-label="Select row {{ row.id }}"></td>{% endif %}
__RIO_TBODY_CELLS__
        <td class="col-act">
          {% if not read_only %}
          <span class="rio-row-actions">
            <a class="rio-iconbtn rio-iconbtn--sm" href="/admin/{{ admin_name }}/{{ row.id }}/edit" aria-label="Edit">{{ icon("pencil") }}</a>
            <a class="rio-iconbtn rio-iconbtn--sm" href="/admin/{{ admin_name }}/{{ row.id }}/delete" aria-label="Delete" style="color:var(--rio-danger)">{{ icon("trash") }}</a>
          </span>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
  <div class="rio-board-foot">
    <span style="font-size:13px;color:var(--rio-text-mute)">Showing <strong style="color:var(--rio-text-hi);font-weight:600">{{ rows|length }}</strong> of <strong style="color:var(--rio-text-hi);font-weight:600">{{ total_rows }}</strong> {{ display_name|lower }}</span>
    {% if total_pages > 1 %}
    <nav class="rio-pagination" aria-label="Pagination">
      {% if prev_page_link %}<a class="rio-page" href="{{ prev_page_link }}" aria-label="Previous">{{ icon("arrow-left") }}</a>{% endif %}
      {% for item in page_items %}{% if item.kind == "ellipsis" %}<span class="rio-page rio-page--ellipsis">…</span>{% elif item.is_active %}<span class="rio-page" aria-current="page">{{ item.number }}</span>{% else %}<a class="rio-page" href="{{ item.link }}">{{ item.number }}</a>{% endif %}{% endfor %}
      {% if next_page_link %}<a class="rio-page rio-page--next" href="{{ next_page_link }}">Next {{ icon("arrow-right") }}</a>{% endif %}
    </nav>
    {% endif %}
  </div>
  {% else %}
  <div class="rio-empty">
    {{ icon("inbox") }}
    <div class="rio-empty-title">No {{ display_name|lower }} yet</div>
    <div>{% if read_only %}There are no records to display here.{% else %}Add the first {{ singular_name|lower }} to get started.{% endif %}</div>
    {% if not read_only %}<div style="margin-block-start:14px"><a class="rio-btn rio-btn--primary rio-btn--md" href="/admin/{{ admin_name }}/new">{{ icon("plus") }} Add {{ singular_name }}</a></div>{% endif %}
  </div>
  {% endif %}
</div>

{% if not read_only %}</form>{% endif %}
{% endblock %}
"####;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::spec::Spec;
    use crate::toml_lite::Document;

    fn view(toml: &str) -> TableView {
        Spec::new(Document::parse(toml).unwrap())
            .views()
            .pop()
            .expect("one view")
    }

    #[test]
    fn drives_columns_from_the_spec() {
        let v = view(
            "[views.bookings]\nprimary = \"booked_at\"\n\
             secondary = \"customer + phone (stacked), status (badge)\"\n\
             detail = \"notes\"\nhidden = \"id\"\n",
        );
        let t = build_list_template("Salon", &v);
        // header humanised + present; detail/hidden columns absent
        assert!(t.contains(">Booked at</th>"));
        assert!(t.contains(">Customer</th>"));
        assert!(t.contains(">Status</th>"));
        assert!(!t.contains(">Notes</th>"));
        assert!(!t.contains(">Id</th>"));
        // primary links to edit; compose renders members
        assert!(t.contains("rio-cell-primary"));
        assert!(t.contains("row[\"phone\"]"));
        assert!(t.contains("row[\"status\"]"));
        // no leftover placeholders
        assert!(!t.contains("__RIO_"));
    }

    #[test]
    fn chrome_is_preserved_and_balanced() {
        let v = view("[views.bookings]\nprimary = \"id\"\n");
        let t = build_list_template("X", &v);
        // key chrome features survive verbatim
        for needle in [
            "rio-cmdbar",
            "data-rio-bulk",
            "rio-pagination",
            "{% for group in filters %}",
            "{% block content %}",
        ] {
            assert!(t.contains(needle), "missing chrome: {needle}");
        }
        // minijinja block balance (cheap structural guard). Close needles match
        // both plain and whitespace-trimmed forms (`{% end… %}` / `{%- end… %}`),
        // since the framework macros close with `{%- endmacro %}`.
        assert_eq!(count(&t, "{% for "), count(&t, "endfor %}"));
        assert_eq!(count(&t, "{% block "), count(&t, "endblock %}"));
        assert_eq!(count(&t, "{% macro "), count(&t, "endmacro %}"));
        // block-style `{% if %}` (the inline `{%- if -%}` macro guards close with
        // `{%- endif -%}`, excluded from both sides by the trailing-space needles).
        assert_eq!(count(&t, "{% if "), count(&t, "{% endif %}"));
    }

    fn count(hay: &str, needle: &str) -> usize {
        hay.matches(needle).count()
    }
}
