//! Compile a validated spec into a `tokens.css` file.
//!
//! The output targets exactly one rustio-admin seam: `RUSTIO_TOKENS_CSS`. At
//! runtime the framework appends this file *after* its baked CSS bundle, and
//! because later `:root` declarations win, every rule here overrides the default
//! without a recompile and without touching the framework's source. This is the
//! same mechanism `rustio-admin theme generate` is built around.

use crate::allowlist;
use crate::spec::Spec;

/// The banner stamped at the top of every generated file.
pub fn banner(project: &str, kind: &str) -> String {
    format!(
        "/* ============================================================\n\
         \x20* GENERATED by rustio-design — DO NOT EDIT THIS FILE.\n\
         \x20*\n\
         \x20*   {kind}\n\
         \x20*   project: {project}\n\
         \x20*\n\
         \x20* The single source of truth is `rustio.design.toml`.\n\
         \x20* Edit that file, then run `rustio-design build`.\n\
         \x20* Hand edits here are reverted on the next build and flagged\n\
         \x20* by `rustio-design check` (drift detection).\n\
         \x20* ============================================================ */\n"
    )
}

/// Build the full `tokens.css` body.
///
/// `brand_ramp` is the optional CSS emitted by `rustio-admin theme generate`
/// (the WCAG-safe color ramp); when present it is inlined first so the spec's
/// own overrides, which come last, still win.
pub fn build_tokens_css(spec: &Spec, brand_ramp: Option<&str>) -> String {
    let mut out = banner(spec.project_name(), "rustio-admin design tokens");
    out.push('\n');

    if let Some(ramp) = brand_ramp {
        out.push_str("/* ---- WCAG-safe brand ramp (via rustio-admin rio-theme) ---- */\n");
        out.push_str(ramp.trim_end());
        out.push_str("\n\n");
    }

    out.push_str("/* ---- rustio-design overrides (these win — loaded last) ---- */\n");
    out.push_str(":root {\n");

    // Literal brand color, only when we did NOT derive a full ramp.
    if brand_ramp.is_none() {
        if let Some(c) = spec.brand_color() {
            out.push_str(
                "  /* brand color (literal — set [brand].derive = true for a WCAG-safe ramp) */\n",
            );
            for token in [
                "--rio-accent",
                "--rio-brand-accent",
                "--rio-brand-light",
                "--rio-brand-surface",
            ] {
                out.push_str(&format!("  {token}: {c};\n"));
            }
        }
    }

    for t in spec.raw_tokens() {
        // Validation has already passed, so resolution succeeds; skip defensively.
        if let Ok(token) = allowlist::resolve(&t.section, &t.key) {
            out.push_str(&format!("  {token}: {};\n", t.value));
        }
    }

    out.push_str("}\n");

    if let Some(css) = spec.custom_css() {
        out.push_str("\n/* ---- custom_css escape hatch (validated) ---- */\n");
        out.push_str(css.trim());
        out.push('\n');
    }

    out
}
